export const COMPONENT = {
  REST_APPLICATION: Symbol(),
  LOGGER: Symbol(),
  CONFIG: Symbol(),
  DATABASE_CLIENT: Symbol(),
  USER_SERVICE: Symbol(),
  USER_MODEL: Symbol(),
  OFFER_MODEL: Symbol(),
  OFFER_SERVICE: Symbol(),
  COMMENT_MODEL: Symbol(),
  COMMENT_SERVICE: Symbol(),
  OFFER_CONTROLLER: Symbol(),
  EXCEPTION_FILTER: Symbol(),
  USER_CONTROLLER: Symbol(),
  COMMENT_CONTROLLER: Symbol(),
};
